name: rtmp_publisher_example
description: Demonstrates how to use the rtmp_publisher plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rtmp_publisher:
    path: ../

  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5
  video_player: ^2.4.5
  e2e: ^0.7.0+1
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true