name: rtmp_publisher
description: Controlling the camera on Android and iOS plus rtmp live streaming support. Based off the Camera plugin.
version: 0.3.7
homepage: https://github.com/nhancv/flutter_rtmp_publisher

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^2.0.1
  video_player: ^2.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.11.0
  mockito: ^5.0.7

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.app.rtmp_publisher
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: RtmppublisherPlugin
